export const GET_FINANCE_DATA_REQUEST = 'GET_FINANCE_DATA_REQUEST';
export const GET_FINANCE_DATA_SUCCESS = 'GET_FINANCE_DATA_SUCCESS';
export const GET_FINANCE_DATA_FAILURE = 'GET_FINANCE_DATA_FAILURE';